### ISSUE TITLE
Sorting dates

### ISSUE THREAD

**Issue by rodolpheg** [crunchprank/google-sheets-to-html#3]
Hey,

I'm implementing this code for a table where one of the columns contains dates. However, the handy "sort" feature doesn't seem to work for dates. Is there any fix for this?

Thanks! This tools is fantastic!

**Comment by crunchprank** [comment]
Can you provide a demo/example of what you're referring to? I'd like to see the format of the date.

**Comment by rodolpheg** [comment]
Actually, I made it work by doing this:

var rawDate = data.Nf[d].c[2].v.split("/") // find the date in DD/MM/YYYY format in response.getDataTable()
var date = new Date(Number(rawDate[2]),Number(rawDate[1])-1,Number(rawDate[0]))

**Comment by crunchprank** [comment]
Thanks for that update.
