### ISSUE TITLE
Cells containing URLs

### ISSUE THREAD

**Issue by rodolpheg** [crunchprank/google-sheets-to-html#4]
Cells containing URLs don't behave in a way that user may click on the text and be sent to the corresponding web page.

Is there a simple fix for this?

Thanks!

**Comment by pdralston** [comment]
Place your links inside "a" tags. i.e. `<a href="">label</a> `

**Comment by crunchprank** [comment]
Yes, as @pdralston mentioned, you can use HTML to display hyperlinks if you want. See pull request #1 for details.

**Comment by rodolpheg** [comment]
Thanks, I'm not sure why this wasn't working when I tried it, but this is indeed the way to make it work. It was also largely a matter of related to the Google API specifically, so sorry about that.
