### ISSUE TITLE
How to set Auto reload every 30 seconds? 

### ISSUE THREAD

**Issue by sathwikrao575** [crunchprank/google-sheets-to-html#6]
Thank you very cool coding

**Comment by crunchprank** [comment]
I don't plan on implementing a way to auto-reload the web page. If you'd like though, you can easily implement something like this by adding the following meta tag within the `index.html` `<head>` tag.
```
<!-- X being the number of seconds --> 
<meta http-equiv="refresh" content="X" >
```
Do you mind sharing your use case for something like this?

**Comment by crunchprank** [comment]
Closing.
